---

- name: Create netrc file
  sudo: yes
  template:
    src: netrc.j2
    dest: "~/.netrc"
    mode: 0600
  when: create_netrc

- name: Update apt
  sudo: yes
  apt:
    update_cache: yes

- name: Install system packages
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - curl
    - wget
    - build-essential
    - python-software-properties
    - mcrypt
    - git
    - sendmail
    - zip
    - unzip
    - openjdk-7-jdk
    - maven

- name: Update apt again
  sudo: yes
  apt:
    update_cache: yes
