---

- name: Install the mysql packages
  sudo: yes
  apt: name={{ item }} state=installed update_cache=yes
  with_items: mysql_pkgs
  environment: env

- name: Copy the my.cnf file
  sudo: yes
  template: src=my.cnf.j2 dest={{ mysql_conf_dir }}/my.cnf
  notify:
   - restart mysql

- name: Create the directory /etc/mysql/conf.d
  sudo: yes
  file: path=/etc/mysql/conf.d state=directory
  notify:
   - restart mysql

- name: Start the mysql services
  sudo: yes
  service: name={{ mysql_service }} state=started enabled=yes

- name: update mysql root password for all root accounts
  sudo: yes
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname != 'localhost'

- name: Copy .my.cnf file with root password credentials to root user
  sudo: yes
  template: src=.my.cnf.j2 dest=/root/.my.cnf mode=0600

- name: Copy .my.cnf file with root password credentials to any other users
  sudo: yes
  template: src=.my.cnf.j2 dest=/home/{{ item }}/.my.cnf owner={{ item }} group={{ item }} mode=0640
  with_items: mysql_server_cred_users

- name: ensure anonymous users are not in the database
  sudo: yes
  mysql_user: name='' host={{ item }} state=absent
  with_items:
   - localhost
   - "{{ ansible_hostname }}"

- name: remove the test database
  sudo: yes
  mysql_db: name=test state=absent

- name: Create the database's
  sudo: yes
  mysql_db: name={{ item.name }} state=present
  with_items: mysql_db
  when: mysql_db|lower() != 'none'

- name: Create the database users
  sudo: yes
  mysql_user: name={{ item.name }}  password={{ item.pass|default("foobar") }}
              priv={{ item.priv|default("*.*:ALL") }} state=present host={{ item.host | default("localhost") }}
  with_items: mysql_users
  when: mysql_users|lower() != 'none'
